In [1]:
import torch
import torch.functional as F

## 🔹 1. Shape Manipulation & Views

### 1. Reshape a flat tensor

In [ ]:
x = torch.arange(12)
# Turn into shape (3, 4)

x = x.reshape(3,4)
x.shape

torch.Size([3, 4])

### 2. Flatten a 2D tensor

In [4]:
x = torch.tensor([[1, 2], [3, 4]])
x = x.reshape(4,)
x

tensor([1, 2, 3, 4])

### 3. Add a new batch dimension

In [6]:
x = torch.tensor([1, 2, 3])
# Turn into shape (1, 3)

x = x.unsqueeze(0)
x.shape

torch.Size([1, 3])

### 4. Permute image tensor

In [7]:
x = torch.rand(224, 224, 3)
# Turn into (3, 224, 224)

x = x.permute(2,0,1)
x.shape

torch.Size([3, 224, 224])

### 5. Transpose matrix

In [8]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
# Transpose rows and columns

x = x.T
x

tensor([[1, 4],
        [2, 5],
        [3, 6]])

## 🔹 2. Slicing & Indexing

### 1. Select the first row from a tensor

In [11]:
x = torch.arange(12).reshape(3, 4)
# Get first row → shape (4,)
print(x)
print("")
x[0]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])



tensor([0, 1, 2, 3])

### 2. Get the 2nd column from a 2D tensor

In [12]:
x[:, 1]

tensor([1, 5, 9])

### 3. Reverse the rows of a tensor

In [19]:
y = torch.flip(x, dims=[1])
y

tensor([[ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8]])

### 4. Get every 2nd element of a 1D tensor

In [23]:
x = torch.arange(12)

print(x)

print(x[::2])

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([ 0,  2,  4,  6,  8, 10])


In [24]:
# note - we can also do reverse arange like this
x = torch.arange(12,1, -1)

### 5. Replace all negative values with zero

In [25]:
x = torch.tensor([-1, 3, -5, 2])

y = torch.clamp(x, min=0)
y

tensor([0, 3, 0, 2])

##  🔹 3. Broadcasting Logic
🎯 Goal: Predict shapes and perform operations on different shapes

### 1. Add a (4, 1) tensor to a (1, 5) tensor → result?

In [ ]:
a = torch.tensor([
    [1] , [2] , [3] , [4]
])
b = torch.tensor([1,2,3,4,5])

a+b 

# note --- here both of them get broadcasted to each other
# they get 4 rows and 5 cols

tensor([[2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7],
        [4, 5, 6, 7, 8],
        [5, 6, 7, 8, 9]])

### 2. Multiply a tensor of shape (3, 1, 4) by (1, 5, 1)

In [28]:
# 3 rows -> each has 1row -> each has 4 elems
a = torch.tensor([
    [[1,2,3,4]],
    [[2,3,4,5]],
    [[4,5,6,7]]
])

# 1 rows -> has 5 rows -> each has 1 elems
b = torch.tensor([[
    [1],
    [2],
    [3],
    [4],
    [5]
]])

z = a * b
z.shape

torch.Size([3, 5, 4])

### 3. Broadcast and subtract a vector from each row

In [29]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]]) # it has shape 2,3
v = torch.tensor([1, 1, 1]) # it has shape 3,

x-v

tensor([[0, 1, 2],
        [3, 4, 5]])

## 🔹 4. Expand vs Repeat vs Repeat Interleave

🎯 Goal: Understand when and how to stretch vs copy data

### 1. Use .expand() to broadcast (3,1,1) into (3,4,2)

In [31]:
x = torch.rand(3,1,1)
print(x.shape)
x = x.expand(3,4,2)
print(x.shape)


torch.Size([3, 1, 1])
torch.Size([3, 4, 2])


### 2. Use .repeat() to tile a (2, 2) matrix into (4, 6)

In [32]:
y = torch.rand(2,2)
print(y.shape)

y = y.repeat(2,3)
print(y.shape)

torch.Size([2, 2])
torch.Size([4, 6])


### 3. Convert [1, 2, 3] to [1, 1, 2, 2, 3, 3]

In [33]:
z = torch.tensor([1,2,3])
z = z.repeat_interleave(2)
z

tensor([1, 1, 2, 2, 3, 3])

### 4. Repeat [1, 2, 3] → [1, 2, 3, 1, 2, 3]

In [34]:
z = torch.tensor([1,2,3])
z = z.repeat(2)
z

tensor([1, 2, 3, 1, 2, 3])