In [2]:
import torch

In [3]:
# Q1: Create a 3x4 tensor of random values from a normal distribution with mean=0 and std=1
# Then convert it to run on GPU if available

a = torch.randn(3,4)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor = a.to(device)

print(a)

tensor([[-0.1753, -2.0216,  0.3046, -0.6500],
        [ 0.0166,  0.6468,  0.2631, -1.1282],
        [-0.0263,  0.3400, -0.6799, -0.1814]])


In [4]:

# Q2: Create a tensor containing values from 0 to 11 (inclusive), then reshape it to a 3x4 matrix
# What's the difference between using dtype=torch.float vs torch.float32?

# Your code here

a = torch.arange(0,12)
print(a)
a = a.reshape(3,4)
print(a)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [5]:
# Q3: Given a batch of 10 images (each 3x28x28), reshape it for a linear layer that expects [batch_size, features]
images = torch.rand(10, 3, 28, 28)

images = images.view(images.size(0) , -1)
images


# Explanation:
# images.size(0) gets the batch size (10 in this case).

# -1 tells PyTorch to infer the remaining dimension (3*28*28 = 2352).

# .view(...) is used to reshape the tensor.

tensor([[1.0702e-01, 8.2573e-01, 9.8399e-01,  ..., 5.1761e-01, 5.4951e-01,
         1.1465e-01],
        [8.4487e-01, 6.3307e-01, 5.1034e-01,  ..., 5.1491e-01, 2.7994e-01,
         5.6022e-01],
        [8.1599e-05, 1.1812e-02, 7.6539e-01,  ..., 4.5400e-01, 9.5237e-01,
         6.7598e-01],
        ...,
        [4.1425e-01, 2.2368e-01, 9.1491e-01,  ..., 1.2090e-01, 6.5530e-01,
         4.6776e-01],
        [7.6319e-01, 4.6062e-01, 6.8564e-02,  ..., 9.5889e-01, 5.9045e-01,
         5.9571e-01],
        [6.6688e-02, 2.0688e-02, 2.0247e-01,  ..., 9.4749e-01, 5.8343e-01,
         2.5525e-01]])

In [6]:
# Q4: Add a "channel" dimension to a 2D grayscale image tensor of shape [28, 28]
img = torch.rand(28, 28)
print(img.shape)
img = img.unsqueeze(0)
print(img.shape)

img = img.repeat(3, 1, 1)
img.shape

torch.Size([28, 28])
torch.Size([1, 28, 28])


torch.Size([3, 28, 28])

In [7]:
# Q5: Convert tensor of shape [batch_size, seq_len, hidden_size] to [seq_len, batch_size, hidden_size]
# (common operation in RNNs)
x = torch.rand(32, 10, 512)  # [batch_size, seq_len, hidden_size]

x = x.permute(1, 0, 2)
x.shape

torch.Size([10, 32, 512])

In [8]:
# Q6: Extract all even-indexed columns from the following matrix
matrix = torch.tensor([[1, 2, 3, 4, 5, 6],
                       [7, 8, 9, 10, 11, 12]])

matrix = matrix[:, ::2]
matrix

tensor([[ 1,  3,  5],
        [ 7,  9, 11]])

In [9]:
# Q7: For this tensor, set all negative values to zero without using loops
data = torch.tensor([[-1, 2, -3], [4, -5, 6]])

data = torch.clamp(data, min=0)
data

tensor([[0, 2, 0],
        [4, 0, 6]])

In [10]:
# Q8: Extract elements from this tensor where the corresponding mask is True
tensor = torch.tensor([1, 2, 3, 4, 5])
mask = torch.tensor([True, False, True, False, True])


# Extract elements where mask is True
selected = tensor[mask]

print(selected)  # Output: tensor([1, 3, 5])

tensor([1, 3, 5])


In [11]:
# Q9: Add a different bias to each channel of this batch of images without loops
# image shape: [batch_size, channels, height, width]
images = torch.rand(8, 3, 32, 32)
channel_biases = torch.tensor([0.5, -0.5, 0.2])

b = channel_biases.unsqueeze(0)
b = b.unsqueeze(-1).unsqueeze(-1)

print(b.shape)



# OR WE HAVE ANOTHER BETTER WAY TO DO THIS 


biases = channel_biases.view(1, -1, 1, 1)
print(biases.shape)
result = images + biases
# Means:
# - 1: batch dimension (so PyTorch broadcasts the same biases to all images)
# - -1: keep the number of channels (PyTorch infers it from the original tensor, which is 3 here)
# - 1: height (will be broadcast across all pixels vertically)
# - 1: width  (will be broadcast across all pixels horizontally)

torch.Size([1, 3, 1, 1])
torch.Size([1, 3, 1, 1])


In [12]:

# Q10: Multiply each row of matrix A by the corresponding element in vector b
A = torch.rand(5, 3)  # 5 rows, 3 columns
b = torch.tensor([1, 2, 3, 4, 5])  # 5 elements

b = b.unsqueeze(-1)
print(b.shape)

A*b



# OR WE COULD HAVE DONE THIS

# Reshape b to [5, 1] to broadcast along columns
b_reshaped = b.view(-1, 1)
print(b_reshaped.shape)
# Multiply each row of A by the corresponding element in b
result = A * b_reshaped


torch.Size([5, 1])
torch.Size([5, 1])


In [13]:
# Q14: Create a 3x3 identity matrix, then use both expand() and repeat() to create a 
# batch of 5 identical matrices. 
identity = torch.eye(3)


batch_expand = identity.unsqueeze(0).expand(5, 3, 3)
batch_repeat = identity.unsqueeze(0).repeat(5, 1, 1)


print("batch_expand shape:", batch_expand.shape)
print("batch_repeat shape:", batch_repeat.shape)


print("Memory usage (expand):", batch_expand.element_size() * batch_expand.nelement(), "bytes")
print("Memory usage (repeat):", batch_repeat.element_size() * batch_repeat.nelement(), "bytes")

batch_expand shape: torch.Size([5, 3, 3])
batch_repeat shape: torch.Size([5, 3, 3])
Memory usage (expand): 180 bytes
Memory usage (repeat): 180 bytes


In [14]:
# Shape: (3, 1, 4)
a = torch.rand(3, 1, 4)
# Shape: (2, 4) - aligned from right: (1, 2, 4) vs (3, 1, 4)
b = torch.rand(2, 4)

a+b

tensor([[[0.2251, 0.4902, 1.0756, 0.7053],
         [1.0119, 0.8393, 0.6483, 1.2902]],

        [[1.0820, 0.4686, 1.6974, 0.3871],
         [1.8687, 0.8177, 1.2701, 0.9721]],

        [[0.5868, 0.6250, 1.4764, 0.5411],
         [1.3735, 0.9741, 1.0492, 1.1260]]])